version: "3"
services:
  mysql_slave1:
    image: mysql:8.0.20
    container_name: mysql-slave1
    restart: unless-stopped
    command:
      - --server-id=2 # 设置MySQL服务器的唯一标识
      - --relay-log-index=slave-relay-bin.index # 设置中继日志索引的文件名
      - --relay-log=relay-log # 开启中继日志
      - --log-bin=master-log # 开启二进制日志
      - --read_only=ON # 启用只读属性
      - --relay_log_purge=0 # 是否自动清空不再需要中继日志
      - --log-slave-updates=1 # 开启从服务器记录二进制日志更新的功能
      - --max_connections=200 # 设置最大连接数
      - --max_connect_errors=10 # 设置最大连接错误数
      - --character-set-server=utf8 # 设置服务器默认字符集为utf8
      - --default-storage-engine=INNODB # 设置默认的存储引擎为InnoDB
      - --default_authentication_plugin=mysql_native_password # 设置默认的身份验证插件为mysql_native_password
      - --log_slave_updates=1 # 开启从服务器记录二进制日志更新的功能
      - --binlog-ignore-db=information_schema # 忽略复制的数据库
      - --binlog-ignore-db=performance_schema # 忽略复制的数据库
      - --binlog-ignore-db=sys # 忽略复制的数据库
      - --binlog-ignore-db=mysql # 忽略复制的数据库
      - --skip-name-resolve # 禁用主机名解析
      - --innodb_flush_log_at_trx_commit=1 # 每次事务提交时刷新日志缓冲区内容到磁盘
      - --sync-binlog=1 # 立即将binlog写入磁盘
      - --innodb_flush_method=O_DIRECT # 设置InnoDB的日志刷新方式为直接刷新
      - --gtid_mode=on # 开启全局事务标识
      - --enforce_gtid_consistency=on # 强制全局事务标识的一致性
      - --binlog_format=mixed # 设置二进制日志的格式为混合模式
      - --sync_binlog=1 # 立即将binlog写入磁盘
      - --default_storage_engine=InnoDB # 设置默认的存储引擎为InnoDB
      - --performance_schema_max_table_instances=400 # 设置性能模式中最大的表实例数
      - --table_definition_cache=400 # 设置表定义缓存的大小
      - --skip-external-locking # 跳过外部锁定
      - --max_allowed_packet=100G # 设置数据包的最大大小
      - --table_open_cache=512 # 设置表缓存的大小
      - --sort_buffer_size=2M # 设置排序缓冲区的大小
      - --net_buffer_length=4K # 设置网络缓冲区的长度
      - --read_buffer_size=2M # 设置读缓冲区的大小
      - --read_rnd_buffer_size=256K # 设置随机读缓冲区的大小
      - --thread_cache_size=64 # 设置线程缓存的大小
      - --tmp_table_size=64M # 设置临时表的大小
      - --lower_case_table_names=1 # 设置表名是否区分大小写，1表示不区分大小写
      - --sql-mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES # 设置SQL模式
      - --explicit_defaults_for_timestamp=true # 如果设置为true，则对于TIMESTAMP列，使用显式DEFAULT CURRENT_TIMESTAMP和ON UPDATE CURRENT_TIMESTAMP定义
      - --skip-name-resolve # 跳过DNS解析
      - --open_files_limit=65535 # 设置可打开文件的数量限制
      - --binlog_expire_logs_seconds=600000 # 当二进制日志文件超过指定秒数时，将被自动删除
      - --slow_query_log=1 # 启用慢查询日志
      - --long_query_time=3 # 设置超过指定秒数的查询将被认为是慢查询
      - --log_queries_not_using_indexes=on # 记录未使用索引的查询
      - --innodb_buffer_pool_size=512M # 设置InnoDB缓冲池的大小
      - --innodb_log_file_size=256M # 设置InnoDB日志文件的大小
      - --innodb_log_buffer_size=64M # 设置InnoDB日志缓冲区的大小
      - --innodb_flush_log_at_trx_commit=1 # 每次事务提交时，是否将日志缓冲区的内容刷新到磁盘
      - --innodb_lock_wait_timeout=50 # 设置InnoDB锁等待超时时间
      - --innodb_max_dirty_pages_pct=90 # 设置InnoDB脏页的最大百分比
      - --innodb_read_io_threads=8 # 设置InnoDB读线程的数量
      - --innodb_write_io_threads=8 # 设置InnoDB写线程的数量
      - --master_info_repository=TABLE #指定存储主服务器信息的文件的类型
      - --relay_log_info_repository=FILE
    ports:
      - "33062:3306" # 将容器的3306端口映射到主机的33062端口
    environment:
      MYSQL_ROOT_PASSWORD: 1024 # root用户密码
      MYSQL_MASTER_HOST: 192.168.1.10 # 指定主服务器的地址
      MYSQL_MASTER_PORT: 33061 # 指定主服务器的端口
      MYSQL_MASTER_USER: root # 主服务器的root用户
      MYSQL_MASTER_PASSWORD: 1024 # 主服务器的root密码
      TZ: "Asia/Shanghai" # 设置时区
    volumes:
      - ./mysql:/var/lib/mysql # 将本地的slave1目录挂载到容器的/var/lib/mysql目录中
