global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'xfg-dev-tech'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 注意IP换为你的应用IP:Port
      - targets: [ '192.168.1.105:8091' ]