{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tomcat - 最大连接数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_connections_config_max_connections{job=\"xfg-dev-tech\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tomcat - 最大线程数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_threads_config_max_threads{job=\"xfg-dev-tech\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tomcat-占用连接数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_connections_current_connections{job=\"xfg-dev-tech\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tomcat - 实时连接数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "tomcat_connections_current_connections{job=\"xfg-dev-tech\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "压测 - 查询订单信息",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(uri, exception, job) (increase(http_server_requests_seconds_count{uri=~\"/api/hystrix/query_order_info\", method=\"GET\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "压测 - 异步请求并发",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(uri, exception) (increase(http_server_requests_seconds_count{uri=~\"/api/hystrix/stream\", method=\"GET\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "压测-查询订单耗时",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (uri) (increase(http_server_requests_seconds_sum{uri=~\"/api/hystrix/query_order_info\"}[1m]))\n/sum by (uri) (increase(http_server_requests_seconds_count{uri=~\"/api/hystrix/query_order_info\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "压测-异步应答耗时",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (uri) (increase(http_server_requests_seconds_sum{uri=~\"/api/hystrix/stream\"}[1m]))\n/sum by (uri) (increase(http_server_requests_seconds_count{uri=~\"/api/hystrix/stream\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}