version: '3.9'
services:
  zoo1:
    image: zookeeper:3.9.2
    container_name: zookeeper
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
