FROM centos:7
MAINTAINER yuanyuan
RUN mkdir -p /usr/local/java
ADD jdk-17_linux-x64_bin.tar.gz /usr/local/java/
CMD yum install freetype fontconfig
ENV JAVA_HOME=/usr/local/java/jdk-17.0.12
ENV PATH=$PATH:$JAVA_HOME/bin
